name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      working-directory: ./terraform  # Especifica o diretório dos arquivos Terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: ./terraform  # Especifica o diretório dos arquivos Terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./terraform  # Especifica o diretório dos arquivos Terraform
      run: terraform plan
